name: follow_read
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.2
  path: ^1.8.3
  http: ^1.2.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  json_annotation: ^4.9.0
  logger: ^2.0.2+1
  drift: ^2.14.1
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  flutter_cache_manager: ^3.3.0
  intl: ^0.18.0
  fluttertoast: ^8.2.3
  shared_preferences: ^2.2.3
  flutter_riverpod: ^2.4.8
  riverpod_annotation: ^2.4.8
  go_router: ^14.0.4
  dartz: ^0.10.1
  dart_mappable: ^4.5.0
  flutter_svg: ^2.0.7
  flutter_html: ^3.0.0
  html: ^0.15.1
  collection: ^1.17.2
  async: ^2.11.0
  url_launcher: ^6.2.3
  photo_view: ^0.14.0
  workmanager: ^0.5.1
  easy_refresh: ^3.4.0
  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.4.8
  visibility_detector: ^0.4.0+2
  dio: ^5.8.0+1
  share_plus: ^7.2.1
  get: 4.7.2
  get_storage: ^2.1.1
  flutter_js: ^0.8.5
  webview_flutter: ^4.9.0
  video_player: ^2.10.0
  chewie: ^1.11.3
  webfeed: ^0.8.0
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  drift_dev: ^2.14.1
  json_serializable: ^6.7.0
  dart_mappable_builder: ^4.5.0
  flutter_launcher_icons: ^0.13.1
  riverpod_generator: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
    - assets/icons/
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
    - family: DMMono
      fonts:
        - asset: assets/fonts/DMMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMMono-Medium.ttf
          weight: 500
    - family: DMSerif
      fonts:
        - asset: assets/fonts/DMSerifDisplay-Regular.ttf
          weight: 400

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png" # 你的1024x1024图标路径

  # 可选 - Android 自适应图标
  android_adaptive_icon_background: "#FFFFFF"
  android_adaptive_icon_foreground: "assets/icons/foreground.png"


